# Generated by Django 4.0.4 on 2022-04-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titel',
        ),
    ]
