# Generated by Django 4.0.4 on 2022-04-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_rename_title_book_titel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_aythor',
            field=models.ImageField(blank=True, default='static/image/p1', null=True, upload_to='media\\photos'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo_book',
            field=models.ImageField(blank=True, null=True, upload_to='media\\photos'),
        ),
    ]
