# Generated by Django 4.0.4 on 2022-04-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_book_photo_aythor_alter_book_photo_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_aythor',
            field=models.ImageField(blank=True, default='static/image/p1', null=True, upload_to='photos'),
        ),
    ]
