# Generated by Django 4.0.4 on 2022-04-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_book_photo_aythor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_aythor',
            field=models.ImageField(blank=True, default='static/image/p1', null=True, upload_to='photos/'),
        ),
    ]
